### PR TITLE
Force h5py version to 2.10.0

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This is a very lazy fix!!

**Comment by alejoe91** [comment]
I know!!! Very proud of it eheheh

**Comment by samuelgarcia** [comment]
I think you should deal with it. In neo we will certainly force to 3.0 when fixed. So it will not possible to have neo/elephant with mearec but mearec depend on it!!!

**Comment by alejoe91** [comment]
Is it fixed already? Of course I plan to fix it, but for now at least it's not broken.

**Pull request merged**
