### PR TITLE
check and correct alignment of espikes

### PR DESCRIPTION
**Pull request by alejoe91**
@samuelgarcia this shuld fix https://github.com/alejoe91/MEArec/issues/45

Instead of aligning spikes when generating recordings, I make sure that templates are aligned. I left a tolerance of 3 samples (< 100 us). That should be ok!

### CODE REVIEW

**Comment by samuelgarcia** [comment]
You solve by selection, rigth ? Not by adding a shift ?

**Comment by alejoe91** [comment]
No, this adds a shift! See here: https://github.com/alejoe91/MEArec/blob/master/MEArec/simulate_cells.py#L781-L819

**Comment by samuelgarcia** [comment]
Cool. Why don't you ptuh tol =1 to have the exact true peak index for all cells ?
I am sorry to insist, it is a very pesonnal need. :)

**Comment by alejoe91** [comment]
ok I can do that :) making a new PR

**Comment by alejoe91** [comment]
https://github.com/alejoe91/MEArec/pull/47

**Pull request merged**
